modLoader="javafml"
loaderVersion="[34,)"
license="MIT"

[[mods]]
modId="zentweaker"
version="${file.jarVersion}"
displayName="ZenTweaker"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/zentweaker"
description=""

[[dependencies.zentweaker]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.4.1, 4)"
    ordering="BEFORE"
    side="BOTH"
