modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="zentweaker"
version="${file.jarVersion}"
displayName="ZenTweaker"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/zentweaker"
description=""

[[dependencies.zentweaker]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.7, 2.11)"
    ordering="BEFORE"
    side="BOTH"
